notifications:
    email: false

    #Install a Terraform executable locally
    before_install:
      - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
       - unzip terraform_0.10.6_linux_amd64.zip

		#These two steps will effectively validate our terraform and output a list of any changes to be made to our infrastructure
		script:
			- ./terraform init ./terraform
			- ./terraform plan ./terraform
