notifications:
  email: false

before_install:
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64.zip

script:
  - ./terraform init ./terraform
  - ./terraform plan ./terraform

